In [14]:
import pandas as pd
from pathlib import Path

In [25]:
df = pd.read_csv('activities.csv', sep=';', index_col=0)
df

,"T(A, x)","T(A, y)","T(A, z)","T(G, x)","T(G, y)","T(G, z)","T(M, x)","T(M, y)","T(M, z)","RA(A, x)",...,"LL(A, y)","LL(A, z)","LL(G, x)","LL(G, y)","LL(G, z)","LL(M, x)","LL(M, y)","LL(M, z)",Subject,Activity
0,8.13050,1.03490,5.42170,-0.009461,0.001915,-0.003424,-0.78712,-0.069654,0.157300,0.70097,...,-9.0812,2.6220,-0.000232,-0.012092,-0.004457,0.74017,0.30053,-0.057730,1,1
1,8.13050,1.02020,5.38430,-0.009368,0.023485,0.001953,-0.78717,-0.068275,0.158900,0.71829,...,-9.0737,2.6218,-0.014784,-0.016477,0.002789,0.73937,0.30183,-0.057514,1,1
2,8.16040,1.02010,5.36220,0.015046,0.014330,0.000204,-0.78664,-0.068277,0.158790,0.69849,...,-9.0886,2.6366,-0.012770,0.005717,-0.007918,0.73955,0.30052,-0.057219,1,1
3,8.16030,1.00520,5.37700,0.006892,0.018045,0.005649,-0.78529,-0.069849,0.159120,0.72799,...,-9.0811,2.6070,-0.005725,0.009620,0.006555,0.74029,0.30184,-0.057750,1,1
4,8.16050,1.02750,5.34730,0.008811,0.030433,-0.005346,-0.78742,-0.068796,0.159160,0.71572,...,-9.0737,2.6218,-0.003929,-0.008371,0.002816,0.73845,0.30090,-0.057527,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1139995,16.00800,-2.01660,-0.58220,2.027100,1.656800,0.584410,-0.73195,-0.476070,-0.013494,16.43100,...,4.3231,-4.5931,-0.230600,0.180890,-2.082300,0.56876,0.39409,0.518170,8,19
1139996,8.28230,-0.69936,0.48698,2.887900,1.603900,-0.020417,-0.73055,-0.472470,-0.012385,7.01620,...,1.2551,-4.1113,1.817200,0.312510,-1.021600,0.53822,0.43745,0.504010,8,19
1139997,2.71210,0.49967,0.84053,1.996400,1.465800,-0.072605,-0.72533,-0.478630,-0.012810,-4.55400,...,15.6940,1.2942,1.842100,0.349400,-0.282080,0.51752,0.47280,0.489250,8,19
1139998,2.03080,-0.71349,-0.11264,1.766100,1.010300,-0.102120,-0.71933,-0.482240,-0.011469,-6.85690,...,-7.4632,-12.3640,-0.150260,1.563400,-0.368450,0.50440,0.51029,0.446480,8,19
1139999,-0.04915,0.76302,-0.19343,2.590200,0.179090,0.011850,-0.71592,-0.483020,0.022000,-6.80130,...,15.0540,7.0935,-3.677800,0.151150,-0.740350,0.47028,0.43618,0.545110,8,19

In [26]:
# Building a new dataframe
new_df = pd.DataFrame()
new_df['Activity'] = df['Activity']
new_df['Subject'] = df['Subject']

In [27]:
# Aggregate together data from sensor ACC captured in 5 different body's part.
new_df['ACC x'] = df['T(A, x)'] + df['RA(A, x)'] + df['LA(A, x)'] + df['RL(A, x)'] + df['LL(A, x)']
new_df['ACC y'] = df['T(A, y)'] + df['RA(A, y)'] + df['LA(A, y)'] + df['RL(A, y)'] + df['LL(A, y)']
new_df['ACC z'] = df['T(A, z)'] + df['RA(A, z)'] + df['LA(A, z)'] + df['RL(A, z)'] + df['LL(A, z)']

In [28]:
# Aggregate together data from sensor GYR captured in 5 different body's part.
new_df['GYR x'] = df['T(G, x)'] + df['RA(G, x)'] + df['LA(G, x)'] + df['RL(G, x)'] + df['LL(G, x)']
new_df['GYR y'] = df['T(G, y)'] + df['RA(G, y)'] + df['LA(G, y)'] + df['RL(G, y)'] + df['LL(G, y)']
new_df['GYR z'] = df['T(G, z)'] + df['RA(G, z)'] + df['LA(G, z)'] + df['RL(G, z)'] + df['LL(G, z)']

In [29]:
# Aggregate together data from sensor MAG captured in 5 different body's part.
new_df['MAG x'] = df['T(M, x)'] + df['RA(M, x)'] + df['LA(M, x)'] + df['RL(M, x)'] + df['LL(M, x)']
new_df['MAG y'] = df['T(M, y)'] + df['RA(M, y)'] + df['LA(M, y)'] + df['RL(M, y)'] + df['LL(M, y)']
new_df['MAG z'] = df['T(M, z)'] + df['RA(M, z)'] + df['LA(M, z)'] + df['RL(M, z)'] + df['LL(M, z)']

In [30]:
# Deleting outliers capture by ACC
indexes = new_df.loc[new_df['ACC x'] > 50].index
new_df.drop(indexes, inplace=True)
indexes = new_df.loc[new_df['ACC x'] < -50].index
new_df.drop(indexes, inplace=True)

indexes = new_df.loc[new_df['ACC y'] > 50].index
new_df.drop(indexes, inplace=True)
indexes = new_df.loc[new_df['ACC y'] < -50].index
new_df.drop(indexes, inplace=True)

indexes = new_df.loc[new_df['ACC z'] > 50].index
new_df.drop(indexes, inplace=True)

indexes = new_df.loc[new_df['ACC z'] < -50].index
new_df.drop(indexes, inplace=True)

In [31]:
# Deleting outliers capture by GYR
indexes = new_df.loc[new_df['GYR x'] > 10].index
new_df.drop(indexes, inplace=True)
indexes = new_df.loc[new_df['GYR x'] < -10].index
new_df.drop(indexes, inplace=True)

indexes = new_df.loc[new_df['GYR y'] > 10].index
new_df.drop(indexes, inplace=True)
indexes = new_df.loc[new_df['GYR y'] < -10].index
new_df.drop(indexes, inplace=True)

indexes = new_df.loc[new_df['GYR z'] > 10].index
new_df.drop(indexes, inplace=True)
indexes = new_df.loc[new_df['GYR z'] < -10].index
new_df.drop(indexes, inplace=True)

In [32]:
# Checking if there are NaN values.
new_df.isnull().any()

Activity    False
Subject     False
ACC x       False
ACC y       False
ACC z       False
GYR x       False
GYR y       False
GYR z       False
MAG x       False
MAG y       False
MAG z       False
dtype: bool

In [33]:
new_df

,Activity,Subject,ACC x,ACC y,ACC z,GYR x,GYR y,GYR z,MAG x,MAG y,MAG z
0,1,1,5.92767,-1.65370,18.95477,-0.006238,-0.015878,-0.038254,-0.53764,-0.240494,-0.075594
1,1,1,5.92959,-1.74260,18.89768,-0.011134,0.002558,-0.015154,-0.53752,-0.233245,-0.071104
2,1,1,5.92739,-1.71680,18.90550,0.014435,0.011941,-0.016073,-0.53973,-0.237137,-0.075123
3,1,1,5.98639,-1.70500,18.84810,0.018648,0.041053,0.000366,-0.56724,-0.246849,-0.105868
4,1,1,5.97912,-1.69180,18.85393,-0.017254,0.019668,-0.001110,-0.53635,-0.238626,-0.070397
...,...,...,...,...,...,...,...,...,...,...,...
1139994,19,8,-7.48100,-1.32740,0.10600,5.342700,-2.735840,-0.338210,0.68606,-0.359100,-0.080237
1139995,19,8,-15.16100,11.03850,-20.12750,5.554180,1.227394,0.622390,0.53623,-0.023682,-0.006403
1139996,19,8,-21.30240,32.25714,10.33298,6.908930,0.749020,-0.843757,0.37812,0.366600,0.084995
1139998,19,8,-2.37223,39.58631,-5.41944,3.860440,3.559620,-2.401520,0.15107,0.572670,-0.154697
1139999,19,8,-4.92589,34.61402,16.70087,1.148010,1.892284,-5.494600,0.11290,0.407180,-0.081932

In [34]:
# Saving the cleaned dataframe, so we can easly use it.
filepath = Path('activities_cleaned.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
new_df.to_csv(filepath, sep=';')