In [1]:
import pandas as pd
from pathlib import Path

In [2]:
df = pd.read_csv('activities.csv', sep=';', index_col=0)

In [3]:
new_df = pd.DataFrame()

In [4]:
new_df['Activity'] = df['Activity']
new_df['Subject'] = df['Subject']

In [5]:
new_df['ACC x'] = df['T(A, x)'] + df['RA(A, x)'] + df['LA(A, x)'] + df['RL(A, x)'] + df['LL(A, x)']
new_df['ACC y'] = df['T(A, y)'] + df['RA(A, y)'] + df['LA(A, y)'] + df['RL(A, y)'] + df['LL(A, y)']
new_df['ACC z'] = df['T(A, z)'] + df['RA(A, z)'] + df['LA(A, z)'] + df['RL(A, z)'] + df['LL(A, z)']

In [6]:
new_df['GYR x'] = df['T(G, x)'] + df['RA(G, x)'] + df['LA(G, x)'] + df['RL(G, x)'] + df['LL(G, x)']
new_df['GYR y'] = df['T(G, y)'] + df['RA(G, y)'] + df['LA(G, y)'] + df['RL(G, y)'] + df['LL(G, y)']
new_df['GYR z'] = df['T(G, z)'] + df['RA(G, z)'] + df['LA(G, z)'] + df['RL(G, z)'] + df['LL(G, z)']

In [7]:
new_df['MAG x'] = df['T(M, x)'] + df['RA(M, x)'] + df['LA(M, x)'] + df['RL(M, x)'] + df['LL(M, x)']
new_df['MAG y'] = df['T(M, y)'] + df['RA(M, y)'] + df['LA(M, y)'] + df['RL(M, y)'] + df['LL(M, y)']
new_df['MAG z'] = df['T(M, z)'] + df['RA(M, z)'] + df['LA(M, z)'] + df['RL(M, z)'] + df['LL(M, z)']

In [8]:
new_df['ACC x'] = round(new_df['ACC x'] / 5, 4)
new_df['ACC y'] = round(new_df['ACC y'] / 5, 4)
new_df['ACC z'] = round(new_df['ACC z'] / 5, 4)

new_df['GYR x'] = round(new_df['GYR x'] / 5, 4)
new_df['GYR y'] = round(new_df['GYR y'] / 5, 4)
new_df['GYR z'] = round(new_df['GYR z'] / 5, 4)

new_df['MAG x'] = round(new_df['MAG x'] / 5, 4)
new_df['MAG y'] = round(new_df['MAG y'] / 5, 4)
new_df['MAG z'] = round(new_df['MAG z'] / 5, 4)

In [9]:
new_df

,Activity,Subject,ACC x,ACC y,ACC z,GYR x,GYR y,GYR z,MAG x,MAG y,MAG z
0,1,1,1.1855,-0.3307,3.7910,-0.0012,-0.0032,-0.0077,-0.1075,-0.0481,-0.0151
1,1,1,1.1859,-0.3485,3.7795,-0.0022,0.0005,-0.0030,-0.1075,-0.0466,-0.0142
2,1,1,1.1855,-0.3434,3.7811,0.0029,0.0024,-0.0032,-0.1079,-0.0474,-0.0150
3,1,1,1.1973,-0.3410,3.7696,0.0037,0.0082,0.0001,-0.1134,-0.0494,-0.0212
4,1,1,1.1958,-0.3384,3.7708,-0.0035,0.0039,-0.0002,-0.1073,-0.0477,-0.0141
...,...,...,...,...,...,...,...,...,...,...,...
1139995,19,8,-3.0322,2.2077,-4.0255,1.1108,0.2455,0.1245,0.1072,-0.0047,-0.0013
1139996,19,8,-4.2605,6.4514,2.0666,1.3818,0.1498,-0.1688,0.0756,0.0733,0.0170
1139997,19,8,-2.1769,12.7338,1.6606,2.4045,0.2775,-0.0504,0.0410,0.0992,0.0080
1139998,19,8,-0.4744,7.9173,-1.0839,0.7721,0.7119,-0.4803,0.0302,0.1145,-0.0309
1139999,19,8,-0.9852,6.9228,3.3402,0.2296,0.3785,-1.0989,0.0226,0.0814,-0.0164

In [10]:
filepath = Path('activities_cleaned.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
new_df.to_csv(filepath, sep=';')